name: Testing Action
permissions: read-all

on: [workflow_dispatch]

jobs:
  scan-main:
    name: Scan code with HLint (main)
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: haskell-actions/hlint-scan@045287572c1462c7a040d5843c3d92559387b545 # main

  scan-v0:
    name: Scan code with HLint (v0)
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: haskell-actions/hlint-scan@045287572c1462c7a040d5843c3d92559387b545 # v0
