name: Ormolu
permissions: read-all

on:
  push:
    paths:
      - '**.hs'
      - '**.lhs'

jobs:
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: haskell-actions/run-ormolu@51664d3a0b156e654b41bcdef917586d5207777f # v13
        with:
          respect-cabal-files: false
          extra-args: '-o -XGHC2021 -o -XOverloadedStrings'
